# Generated by Django 4.2 on 2023-04-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date published',
            new_name='pub_date',
        ),
    ]
