# Generated by Django 4.2 on 2023-05-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_person_user_vote'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('person', 'question'), name='poll_person_question_unique'),
        ),
    ]
